apiVersion: apps # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: valaxy-deployment
spec:
   containers:
     - name: valaxy-devops-project
       image: dileep95/spring:tagVersion
       imagePullPolicy: Always
       ports:
       - containerPort: 8050
